### PR TITLE
fix: reduce scanning for appmap.yml

### LINKED ISSUE #633: High CPU utilization running the VS Code extension
Every second, the extension scans the entire directory tree under the project root, looking for any files named `appmap.yml`. If the tree is big (e.g. `appmap-js`, with a fully-populated `node_modules`), this will cause very high CPU usage.

### PR DESCRIPTION
**Pull request by apotterri**
**This shouldn't be merged until the `wip` commit gets removed. It's only there as a temporary measure to run the integration tests.**

Reduce the cases where the extension scans the entire subtree under the current project directory.

Fixes #633 .

### CODE REVIEW

File: src/services/nodeProcessService.ts [hunk 1]
```diff
@@ -84,22 +84,42 @@ export class NodeProcessService implements WorkspaceService<NodeProcessServiceIn
       }
     };
 
+    const excludes = vscode.workspace.getConfiguration('files').get('watcherExclude') as string[];
```
Comment (dividedmind) [inline src/services/nodeProcessService.ts:87]: Is it really a `string[]`? You seem to be using it with `Object.keys` later, which would give consecutive integers if that was the case.

**Review by dividedmind — CHANGES_REQUESTED** [review]
There is some type weirdness happening there.

Also, I wonder if it wouldn't be a better design to move this logic into the `ConfigFileProvider` instead of littering the watchers with yet another parameter? Feels like it belongs there.

**Comment by apotterri** [comment]
> There is some type weirdness happening there.
> 
> Also, I wonder if it wouldn't be a better design to move this logic into the `ConfigFileProvider` instead of littering the watchers with yet another parameter? Feels like it belongs there.

I didn't put it in `ConfigFileProvider`, because `ConfigFileProvider` is so simple:
```
export type ConfigFileProvider = () => Promise<vscode.Uri[]>;
```
It seems reasonable to expand it with this functionality, though. Let me try it and see what it looks like.

**Comment by dividedmind** [comment]
> > There is some type weirdness happening there.
> > Also, I wonder if it wouldn't be a better design to move this logic into the `ConfigFileProvider` instead of littering the watchers with yet another parameter? Feels like it belongs there.
> 
> I didn't put it in `ConfigFileProvider`, because `ConfigFileProvider` is so simple:
> 
> ```
> export type ConfigFileProvider = () => Promise<vscode.Uri[]>;
> ```
> 
> It seems reasonable to expand it with this functionality, though. Let me try it and see what it looks like.

Thanks! You can probably keep the simple API (at least consumer-side), just put more logic there :)

**Review by dividedmind — APPROVED** [review]
