### PR TITLE
fix: Project language now reflects the preferred language

### LINKED ISSUE #718: Telemetry for reported language should match what the Project Picker determines
This should not be returning/stringifying an array:
https://github.com/getappmap/vscode-appland/blob/master/src/telemetry/definitions/properties.ts#L149

Instead, return the single language we'd be displaying in the project picker.

### PR DESCRIPTION
**Pull request by dustinbyrne**
This PR fixes an issue where project language was being reported as an array of all languages present in the workspace folder. This presented an issue, because there was now no indication of what language the project would be defined as by the project picker.

Resolves #718

### CODE REVIEW

File: src/telemetry/definitions/properties.ts [hunk 1]
```diff
@@ -148,8 +151,12 @@ export const SCANNER_CONFIG_PRESENT = new TelemetryDataProvider({
 
 export const PROJECT_LANGUAGE = new TelemetryDataProvider({
   id: 'appmap.project.language',
-  cache: true,
-  async value(data: { rootDirectory?: string; metadata?: Record<string, unknown> }) {
+  cache: false,
+  async value(data: {
```
Comment (dividedmind) [inline src/telemetry/definitions/properties.ts:155]: You can remove the useless `async` while you're here.

**Review by dividedmind — APPROVED** [review]
Looks ok.

The other commit (with the `initialized` parameter to `onCreate`) seems unrelated and unused, did you mean to include it?
