### PR TITLE
Fix source links with drive letters on Windows

### LINKED ISSUE #840: Some source code links don't work in Windows
Some source code links in the AppMap do not work correctly in Windows in VS Code. They work correctly in JetBrains. For example, clicking on this does nothing:

Image

### PR DESCRIPTION
**Pull request by ahtrotta**
Fixes #840

### CODE REVIEW

File: src/editor/appmapEditorProvider.ts [hunk 1]
```diff
@@ -489,7 +490,18 @@ export default class AppMapEditorProvider
...
+      const parsedLocation = parse(location);
+      const { root } = parsedLocation;
+
+      // Handle the situation where the location is a Windows file path with a drive letter
+      // For example, C:/Users/user/some/directory/file.rb:4
+      if (root.includes(':')) {
+        const driveLetter = tokens.shift();
+        tokens[0] = `${driveLetter}:${tokens[0]}`;
+      }
+
```
Comment (dividedmind) [inline src/editor/appmapEditorProvider.ts:504]: This seems needlessly complicated. How about `const [, path, line] = location.match(/^(.*?)(?::(\d+))?$/)`?

**Review by dividedmind — CHANGES_REQUESTED** [review]

File: src/editor/appmapEditorProvider.ts (hunk 1 above)
Comment (ahtrotta) [reply src/editor/appmapEditorProvider.ts]: Sure, I changed it :+1:
